### PR TITLE
improve openai completions api access

### PR DESCRIPTION
**Pull request by falcucci**
# improve openai completions api access

adds a new `requestbody` struct to the `main.go` file to add a body in a post request.

## problem
the way we parse and build request body to dispatch the request has some limitations which I couldn't fix using the `strings.NewReader` parser.

## solution
the solution to this problem is to add a body to the request using structs. the body contains information such as the model, prompt, temperature, max tokens, top p, frequency penalty, and presence penalty.

## proposed changes
the following changes have been proposed to solve the problem stated above.

* add a struct called requestbody to `main.go`
* instantiate a requestbody object and add the necessary fields
* convert the requestbody object to a json object
* add the json object to the post request

## impact
the impact of these changes is that the post request in main.go will now include a body with the necessary information, which will make the requests valid.

## testing
the changes have been tested and have been proven to work as intended.

to replicate the error just do a tiny change in the source code and run the following command to see the results.

```bash
go run main.go "e.g error using double quotes or special characters. $(git diff)"
```

## additional information
no additional information is necessary.

*run the same command to have good results after pull my changes.*

### CODE REVIEW

**Comment by paij0se** [comment]
I don't really see these changes necessary. I want to keep the tool the smallest and minimalist as possible, but thanks for your proposal!

**Comment by falcucci** [comment]
thank, I'm generating a release with these changes by my own anyway.

I believe that a `cli` which aims to be as good good as chatgpt on terminal should work without any limitation, as I described above.

gg

**Comment by paij0se** [comment]
You know what, you're right. Merged!

**Comment by falcucci** [comment]
thank you for updating the project!

also sorry about the import issues you had after merging, I've updated to release a new patch version since you wasn't going to merge it.

going to use your version again 🥇

**Pull request merged**
